name: "DigitalOcean Doorkeeper"
author: "Jorge Maroto (@patoroco)"
description: "Open or close a specific port in your DigitalOcean firewall."
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  # Input parameters allow you to specify data that the action expects to use during
  # runtime. GitHub stores input parameters as environment variables.
  # Input ids with uppercase letters are converted to lowercase during runtime.

  digitaloceanToken:
    description: "Digital Ocean token"
    required: true

  firewallName:
    description: "Name of the firewall attached to your droplet"
    required: true

  actionToDo:
      description: "'add'/'remove' the Github's IP"
      required: true

  protocol:
    description: "Protocol used by the service to update"
    default: "tcp"

  IP:
    description: "IP that will be added / removed. If it's not set, doorkeeper uses the local ip."

  port:
    description: "Port used by the service to update"
    default: "22"

  dryRun:
    description: "Specify true if you just want to check the action without apply it."
    default: "true"

